name: Auto‑process publications
on:
  push:
    paths:
      - 'content-uploads/**'

permissions:
  contents: write     # give GITHUB_TOKEN write

jobs:
  parse-and-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python deps
      run: pip install bibtexparser

    - name: Parse uploads
      run: |
        python <<'PY'
        import os, json, glob, bibtexparser, pathlib
        out = []
        uploads = pathlib.Path('content-uploads')

        # all json
        for j in uploads.glob('*.json'):
            out.extend(json.loads(j.read_text()))

        # all bib
        for b in uploads.glob('*.bib'):
            db = bibtexparser.load(open(b))
            for e in db.entries:
                out.append({
                    "id": e.get("ID"),
                    "authors": e.get("author","").split(" and "),
                    "title": e.get("title",""),
                    "journal": e.get("journal",""),
                    "year": int(e.get("year","0") or 0),
                    "volume": e.get("volume",""),
                    "number": e.get("number",""),
                    "pages": e.get("pages",""),
                    "doi": e.get("doi",""),
                    "url": e.get("url",""),
                    "topics": []
                })
        pathlib.Path('publications').mkdir(exist_ok=True)
        pathlib.Path('publications/sample_publications.json').write_text(
            json.dumps(out, indent=2)
        )
        PY

    - name: Commit & push
      env:
        GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name  "github‑actions"
        git config --global user.email "github‑actions@github.com"
        git add publications/sample_publications.json
        git commit -m "Auto‑update publications 📚" || exit 0
        git push https://x-access-token:${PAT_PUSH}@github.com/${{ github.repository }}.git \
                HEAD:${{ github.ref }}

